### ISSUE TITLE
NewFeature unequal segment lengths

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#135]
Each borehole should have a certain number of segments to be split into. Each segment should have a length. 

Issue #133 allows for boreholes to have unequal number of segments per borehole. Additionally, each segment length should be definable from a high level API. This issue seeks to address the definition of segment lengths. 

This new feature would allow for `SegmentLengths` of each segment to be defined in addition to the number of segments at each borehole being different.

**Comment by MassimoCimmino** [comment]
I like the idea.

It might be better to consider a `lengthFraction` (list of (nq_i,) arrays) so that the sum of each array is 1, i.e. `np.abs(1 - np.sum(x)) < tol` (using the same length tolerance as currently implemented in the `gFunction` object). In any case, it can be regularized with `x = x/np.sum(x)` when formatting inputs.

Here, I foresee a use case where the same bore field configuration is calculated with different lengths. Having fractions as inputs avoids re-evaluating the length distributions.

A nice feature would be to add some functions in the `utilities` module for some recommended length distributions (to be determined).

As I mentioned in the #134 thread, it might be required to modify [`_find_axial_borehole_pairs()`](https://github.com/MassimoCimmino/pygfunction/blob/369aa2d425c517ffdde86621144e97950034d8f2/pygfunction/gfunction.py#L2036). "Similar" borehole pairs are determined based on `H`, `D`, `r_b`, `nq_i` and now the length fractions.

**Comment by j-c-cook** [comment]
> A nice feature would be to add some functions in the `utilities` module for some recommended length distributions (to be determined).

Glad to hear you would like to see that. It is a current area of research. I think that should be apart of a future PR.

**Comment by MassimoCimmino** [comment]
I just realized there might be some difficulties to make this compatible with the `Pipe` and `Network` objects. I will try to figure something out while working on #132.

**Comment by j-c-cook** [comment]
The [pull request](https://github.com/MassimoCimmino/pygfunction/pull/136) is [merged](https://github.com/MassimoCimmino/pygfunction/pull/136#event-5551061452) .

**Comment by j-c-cook** [comment]
Can you link this issue to [Milestone v2.1](https://github.com/MassimoCimmino/pygfunction/milestone/6)?
