### ISSUE TITLE
1s gfunction evaluation: numpy.linalg.LinAlgError: Singular matrix

### ISSUE THREAD

**Issue by wouterpeere** [MassimoCimmino/pygfunction#231]
When I tried to evaluate a gfunction at 1 second, I got an 'numpy.linalg.LinAlgError: Singular matrix' error.
The problem is, I think, caused by getting a all-zero matrix when calculating the thermal response factors, leading to a singular matrix. Whenever I try to run the code with an evaluation at 2 seconds, the thermal response factors are small (10^-200) but non-zero ...

The code I used was
```Python
import pygfunction as gt

borefield = gt.boreholes.rectangle_field(10, 12, 6, 6, 100, 4, 0.075)
gt.gfunction.gFunction(borefield, 1.25*10**-6, 1.).gFunc
```

**Comment by wouterpeere** [comment]
I can create a function to check if the gfunction evaluation is at too small a timestep and make a PR, if you want to.

**Comment by MassimoCimmino** [comment]
This is an issue I had during the implementation of *g*-functions into [modelica-ibpsa](https://github.com/ibpsa/modelica-ibpsa).

The solution should still return values for all requested times, even if the result is zero. One option is to evaluate a threshold time value (e.g. `min(r_b)^2/(25*alpha)`). Only times above the threshold have their *g*-function calculated. For the times below, the *g*-function is linearized between 0 (at `t=0.`) and the *g*-function at the threshold time.

I am of course open to other ideas.

**Comment by wouterpeere** [comment]
That can be an elegant solution, although linearisation will not solve the problem in and of itself I think. One can evaluate at 0.00001s so it will be 0 even with linearisation.

Shouldn't there be a threshold below which the concept of gfunctions doesn't make sence anymore due to the fact that we are totally in the range of short-term effect?

**Comment by jeffreyspitler** [comment]
Regarding: "Shouldn't there be a threshold below which the concept of gfunctions doesn't make sence anymore due to the fact that we are totally in the range of short-term effect?"
Short time step g-functions (Yavuzturk and Spitler 1999) accounted for the transient conduction inside the borehole, based on 2-d radial-angular conduction, but did not account transit time or 3-dimensional effects.  They worked reasonably well down to about 15 minute time-steps, depending on conditions, but would give aphysical results if the time-step was too low.  This approach does, however, have the advantage of maintaining the same g-function definition, though the resulting borehole wall temperatures at low times might be thought of as an equivalent temperature.

To go lower requires consideration of the transit time effects.  One approach is detailed in Mitchell and Spitler (2020).  This recasts the g-function to give exiting fluid temperatures rather than borehole wall temperatures.

Mitchell, M. S. and J. D. Spitler. 2020. An Enhanced Vertical Ground Heat Exchanger Model for Whole-Building Energy Simulation. Energies 13(16): 4058. https://www.mdpi.com/1996-1073/13/16/4058

Yavuzturk, C. and J. D. Spitler. 1999. A Short Time Step Response Factor Model for Vertical Ground Loop Heat Exchangers. ASHRAE Transactions 105(2): 475-485.

**Comment by wouterpeere** [comment]
@jeffreyspitler The paper you referenced was an interesting read. I think your comment is somewhat related to issues #149 and #44 (about the implementation of short-term g-functions). That would be indeed the most elegant solution in my opinion ...

**Comment by MassimoCimmino** [comment]
Thank you @jeffreyspitler. I also missed the (Mitchell and Spitler 2020) paper.

There are 3 issues discussed here. The first one being the bug (this issue) and the other 2 related to short time steps.

When considering short time steps, there are two classes of g-function definitions :

### (1) The "wall-to-ground" *g*-function
This one relates the effective borehole wall temperature variation (`T_b`) to the heat extracted at the borehole wall (`Q_b`), with `T_b(t) = T_g - Q_b / (2*pi*k_s) * g(t)`. This can be coupled to a short time step model during a simulation to relate the heat extracted from the fluid (`Q_f`) to the heat extracted at the borehole wall (`Q_b) and consider effects such as variable (and intermittent) fluid mass flow rates. This is the approach currently implemented in [modelica-ibpsa](https://github.com/ibpsa/modelica-ibpsa).

### (2) The "fluid-to-ground" *g*-function (sometimes called the *g**-function)
This one relates the effective borehole wall temperature variation (`T_b`) (or sometimes the mean or inlet fluid temperature) to the heat extracted from the fluid (`Q_f`), with `T_b(t) = T_g - Q_f / (2*pi*k_s) * g*(t)`. As @jeffreyspitler pointed out, `T_b` can be an "effective" temperature derived from the steady-state thermal resistance.

When using a steady-state thermal resistance to model the boreholes, the two approaches are equivalent : `Q_b = Q_f`.

Ideally, both will eventually be available in pygfunction. For (1), only the cylindrical correction to the borehole geometry is missing (#44). For (2), we probably need the development of a new module into pygfunction (#149).

**Comment by MassimoCimmino** [comment]
@wouterpeere I fixed the error on the `issue231_singularMatrix` branch. Let me know if that fixes your issues.
