### ISSUE TITLE
Effective borehole thermal resistance of coaxial pipe

### ISSUE THREAD

**Issue by wouterpeere** [MassimoCimmino/pygfunction#263]
I have a question w.r.t. the effective borehole thermal resistance of the coaxial pipe.

In my tests with pygfunction, the Rb* for a coaxial pipe seems independent from the ground thermal conductivity, where this is not the case for a single/double U-tube. I do not know whether this is a bug or it is indeed correct that the Rb* for coaxial pipes is independent from the ground thermal conductivity ...

Best regards,
Wouter Peere

**Comment by MassimoCimmino** [comment]
For a centered coaxial pipe, the (horizontal) thermal resistance R_b is indeed independent of the ground thermal properties since the dimensionless temperature distribution in the borehole is independent of the soil.

For the effective borehole thermal resistance R_b^*, we implement the definition of Hellström (Ph.D. Thesis, 1991) which assumes a uniform borehole wall temperature :
```
R_b^* = R_b * eta * coth(eta)
eta = H / (C_f * V_f) * 1 / (2 * R_b) * sqrt(1 + 4 * R_b / R_12)
```
The value of R_b^* is then only dependent on the ground properties if the delta-circuit thermal resistances (R_b and R_12) are themselves dependent on the soil thermal properties. Note that the implementation of these equations into _pygfunction_ is different, but equivalent.

The soil properties can still influence the borehole wall temperature profile along the borehole. In _pygfunction_, these effects are encapsulated into the _g_-function (and the calculation of the effective borehole wall temperature T_b^*) when using the **Mixed inlet fluid temperatures** (`'MIFT'`) boundary condition.
