### ISSUE TITLE
Mixed series/parallel-coupled boreholes

### ISSUE THREAD

**Issue by jankoc** [MassimoCimmino/pygfunction#46]
The documentation does not seem to be clear with respect to using mixed series/parallel-coupled boreholes with load aggregation, i.e. combining the example "mixed_inlet_conditions.py" with the example "fluid_temperature_multiple_boreholes.py". Is this possible at all, or are there restrictions here? I could not find such restrictions in the documentation.

Example: As there are N inlets (i.e. N series of coupled boreholes), I would have suspected that one should define the load-aggregation with nSources=N. That works fine in itself, but then Loadagg.initialize expects a 54xN array (at least according to section 2.4 in the documentation; 54 is here due to the number of timesteps), while the gfunction for the network (via gt.gfunction.mixed_inlet_temperature)  gives an 54x1 array as output instead of a 54xN array. I've also tried using an array input of mflow to gt.gfunction.mixed_inlet_temperature, but that gives an error message and it looks like the function is not prepared to output a 54xN array.

If one instead uses nSources=1, one gets only one deltaT_b (ground temperature), which can not be correct?  It is also not clear how one should calculate the ground temperature in each borehole with the functions as they are now (e.g. how to evaluate the correct input to Utubes[i].get_temperature()).

**Comment by MassimoCimmino** [comment]
The g-function (mixed inlet) scheme does not represent the conditions around each of the boreholes. Instead, it finds an "effective" heat exchange temperature that produces the correct relation between inlet/outlet fluid temperatures (into the field), effective borehole wall temperature, and total heat extraction rate. As such, there is only one source, only one borehole wall temperature, and only one heat transfer rate. The fluid temperatures evaluated for individual boreholes are then not representative of reality, but that of the whole field is.

Load aggregation should be initialized with only one source (nSources=1). This will represent the heat extraction history of the complete network. You will only get a single "effective" Tb. Coupled with the effective bore field resistance in the network object, it will yield the correct inlet fluid temperature into the field. It will not be possible to plot the temperature profiles along the boreholes since we don't evaluate the borehole temperature of specific boreholes.
