### ISSUE TITLE
Inclined boreholes 

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#50]
Does the most current version account for inclined boreholes? 

Given that the segment-to-segment response factor is calculated by equation 8 (Cimmino and Bernier 2014), how would the distance formula `d_{ij}` be implemented?
![equation_8](https://user-images.githubusercontent.com/39248734/88466475-36e8e080-ce92-11ea-990c-167d8a5ffe7f.png)

For example, currently calculation of `d_{ij}` is given by the equation 11.
![equation_11](https://user-images.githubusercontent.com/39248734/88466551-2edd7080-ce93-11ea-9d68-22d31b5b760b.png)

Would equation 11 need to become `d_{uv}?` Given the implementation of inclined boreholes, could it now be that `x_i == x_u is false`, and `x_j == x_v is false`?

Additionally, the location of segment u,  `(x_u, y_u)` could vary slightly along the segment. Would the method to calculate the distance `d_{uv}` result in the distance from top-to-top, center-to-center, bottom-to-bottom or some other approach?

I'm assuming this implementation would occur in  <a href="https://github.com/MassimoCimmino/pygfunction/blob/982ab6c47dae4931415f1a0f9a43bbfcfb34580c/pygfunction/gfunction.py#L709">_borehole_segments</a>. There has been extensive validation of the analytical implementation of the uniform borehole wall temperature (UBWHT) boundary condition when compared to Eskilson's numerical method for vertical boreholes. Given implementation, inclined boreholes would need compared to some of Eskilson's inclined borehole g-functions. 

---------------------------------------------------------------------------------------------------------------------------------------------------------------- 
Cimmino, Massimo, and Michel Bernier. "A Semi-analytical Method to Generate G-functions for Geothermal Bore Fields." International Journal of Heat and Mass Transfer 70 (2014): 641-50. Web.

**Comment by MassimoCimmino** [comment]
The current version does not account for inclined boreholes.

For inclined boreholes, *h<sub>ij,uv</sub>* becomes a function of the radial and axial distances between segments, as well as their relative tilt and orientation. The FLS solution for such a case was presented in Lazzarotto (2016)­<sup>[1,2]</sup> (and papers cited therein).

The issue faced with the implementation in **pygfunction is regarding [similarities](https://github.com/MassimoCimmino/pygfunction/blob/982ab6c47dae4931415f1a0f9a43bbfcfb34580c/pygfunction/heat_transfer.py#L278), which becomes more complex when adding in two more variables (tilt and orientation). I am unsure if this strategy would even be beneficial for fields of inclined boreholes since it is much less likely that "similar" pairs of segments can be found within the field.

A first approach would be to set `use_similarities=False` if any of the boreholes are inclined.

You are right that `_borehole_segments` should be modified to properly instantiate segments with the proper position, depth, length, orientation and tilt.

---
[1] [Lazzarotto, A. (2014). A network-based methodology for the simulation of borehole heat storage systems. Renewable energy, 62, 265-275.](https://www.sciencedirect.com/science/article/pii/S0960148115303359)
[2] [Lazzarotto, A., & Björk, F. (2016). A methodology for the calculation of response functions for geothermal fields with arbitrarily oriented boreholes–Part 2. Renewable energy, 86, 1353-1361.](https://www.sciencedirect.com/science/article/pii/S0960148115303360)

**Comment by MassimoCimmino** [comment]
Comparisons with Eskilson's *g*-functions are included below.

## Fields of inclined boreholes on one line

### 2 boreholes
![Figure_2](https://user-images.githubusercontent.com/23085996/151082035-c867c9c5-ce1b-45ff-a6f3-a281b4c9c927.png)
![Figure_1](https://user-images.githubusercontent.com/23085996/151082040-282da3c7-a8b7-4abe-8620-9cc063a95e60.png)
![Figure_3](https://user-images.githubusercontent.com/23085996/151082046-319e2cd5-dc54-42bf-90f4-ae42059b8f14.png)

### 4 boreholes
![Figure_6](https://user-images.githubusercontent.com/23085996/151082087-5c40afe9-e5b9-47bd-99db-9d56063b20af.png)
![Figure_5](https://user-images.githubusercontent.com/23085996/151082094-4e3cbd08-dc1d-47e4-9ffc-71661d3249ef.png)
![Figure_7](https://user-images.githubusercontent.com/23085996/151082100-822cf2ab-4d2f-4ee0-ada9-2de94379824d.png)

### 6 boreholes
![Figure_10](https://user-images.githubusercontent.com/23085996/151082122-b2f61e89-56e4-4a46-8b36-e59e5283cc11.png)
![Figure_9](https://user-images.githubusercontent.com/23085996/151082127-a4c99e0c-15be-4e91-8cd1-fc6399a072ee.png)
![Figure_11](https://user-images.githubusercontent.com/23085996/151082132-315f63fa-cf91-41de-8723-3f3ad1d6418f.png)

**Comment by MassimoCimmino** [comment]
## Fields of inclined boreholes in a circle

### 4 boreholes
![Figure_2](https://user-images.githubusercontent.com/23085996/151087724-f5e0a8fc-5390-4342-b41d-82a9bb14e27b.png)
![Figure_1](https://user-images.githubusercontent.com/23085996/151087729-7885368e-13df-4f02-9260-d29f6c1b71fb.png)
![Figure_3](https://user-images.githubusercontent.com/23085996/151087737-81d19d1b-4f28-4a98-9f3b-50cf652c6654.png)

### 6 boreholes
![Figure_6](https://user-images.githubusercontent.com/23085996/151087746-33c76ead-a8bf-47cb-ac63-78acc1e9eb3a.png)
![Figure_5](https://user-images.githubusercontent.com/23085996/151087750-27807d01-6029-41cc-8eaf-773e51e8a66e.png)
![Figure_7](https://user-images.githubusercontent.com/23085996/151087755-b35af6da-cff2-430d-a941-e1d08ef548ee.png)

### 8 boreholes
![Figure_10](https://user-images.githubusercontent.com/23085996/151087770-a8f068b0-0eb9-4cf6-9882-14db71821cea.png)
![Figure_9](https://user-images.githubusercontent.com/23085996/151087775-a50a493d-435b-43e0-9735-71d3a334a41f.png)
![Figure_11](https://user-images.githubusercontent.com/23085996/151087780-0d4a8d2d-0bab-4b0b-a282-12923aadf26d.png)

**Comment by MassimoCimmino** [comment]
## Fields of inclined boreholes in a circle with a borehole in the center

### 4 + 1 boreholes
![Figure_2](https://user-images.githubusercontent.com/23085996/151090361-0d1d4022-51d4-42f5-9883-60b5cf403da1.png)
![Figure_1](https://user-images.githubusercontent.com/23085996/151090379-fda59870-07d9-4c32-b89c-10c2015e0c0a.png)
![Figure_3](https://user-images.githubusercontent.com/23085996/151090386-5e3321e0-ddb2-4b8f-92f8-6992a7f6cd31.png)

### 6 + 1 boreholes
![Figure_6](https://user-images.githubusercontent.com/23085996/151090391-802c15ce-e7ad-4390-9842-93aeaa543b03.png)
![Figure_5](https://user-images.githubusercontent.com/23085996/151090398-4f05db88-2908-464d-adc8-6f1c4bc2044d.png)
![Figure_7](https://user-images.githubusercontent.com/23085996/151090400-49ba8397-a95d-46ef-af86-7691b860fd78.png)

### 8 + 1 boreholes
![Figure_10](https://user-images.githubusercontent.com/23085996/151090426-d1d1e051-c40a-40b9-8e18-7c4b5530f1a8.png)
![Figure_9](https://user-images.githubusercontent.com/23085996/151090432-7ab0c892-010d-4736-bdbd-613f4e226232.png)
![Figure_11](https://user-images.githubusercontent.com/23085996/151090438-ff0c2fa2-70fa-4ca0-9a5b-d1c783b188a6.png)

**Comment by MassimoCimmino** [comment]
## 8 boreholes in a fan-shaped configuration
![Figure_2](https://user-images.githubusercontent.com/23085996/151092885-0f0555eb-20c9-446d-b710-33941997dedf.png)
![Figure_1](https://user-images.githubusercontent.com/23085996/151092891-67c6fbdf-40cb-4850-8fab-e15efdfc573d.png)

## 8 boreholes in an "optimum" configuration
![Figure_4](https://user-images.githubusercontent.com/23085996/151092920-da290a05-8b8e-4b00-9007-cb7c8e558c05.png)
![Figure_3](https://user-images.githubusercontent.com/23085996/151092925-62bfb150-d1ae-4902-a1f8-07a5e5edd455.png)
